/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {Suspense} from "react";
import { useGLTF } from "@react-three/drei/native";
import duck from "./assets/Duck.glb"

export default function Model(props) {
  const { nodes, materials } = useGLTF(duck);
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LOD3spShape.geometry}
          material={materials["blinn3-fx"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(duck);
